/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa3.GUI;
import java.util.Enumeration;
import java.util.HashMap;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import poo.programa3.Configuracion;
import poo.programa3.Reloj;
import poo.programa3.RangeException;

/**
 * Esta ventana implementa la funcionalidad de la configuración
 * @author Daniel Granados Retana y Diego Granados Retana
 */
public class ConfiguracionGUI extends javax.swing.JFrame {
    private String nivel;
    private String reloj;
    private boolean lado;
    private HashMap<String, javax.swing.JRadioButton> niveles = new HashMap<>();
    private HashMap<String, javax.swing.JRadioButton> relojes = new HashMap<>();
    private HashMap<Boolean, javax.swing.JRadioButton> lados = new HashMap<>();
    private HashMap<Integer, javax.swing.JRadioButton> tamaños = new HashMap<>();
    
    /**
     * Creates new form Configuracion
     */
    public ConfiguracionGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        niveles.put("Fácil", facilButton);
        niveles.put("Intermedio", intermedioButton);
        niveles.put("Difícil", dificilButton);
        relojes.put("Sí", siButton);
        relojes.put("Timer", timerButton);
        relojes.put("No", noButton);
        lados.put(false, izquierdaButton);
        lados.put(true, derechaButton);
        tamaños.put(5, CincoButton);
        tamaños.put(6,SeisButton);
        tamaños.put(7, SieteButton);
        tamaños.put(8,OchoButton);
        tamaños.put(9,NueveButton);
        System.out.println(Configuracion.getNivel());
        if (!Configuracion.getNivel().equals("Multinivel")){
              niveles.get(Configuracion.getNivel()).setSelected(true); // obtenemos el objeto del boton respectivo al nivel y lo activamos.
        } else {
              multinivelButton.setSelected(true);
        }
        
        relojes.get(Configuracion.getReloj()).setSelected(true); // obtenemos el objeto del boton respectivo al reloj y lo activamos.
        lados.get(Configuracion.getLado()).setSelected(true); // obtenemos el objeto del boton respectivo al lado y lo activamos.
        tamaños.get(Configuracion.getTamaño()).setSelected(true);
        if (Configuracion.getReloj().equals("No")){
            relojFrame.setVisible(false);
        } else if (Configuracion.getReloj().equals("Sí")){
            relojFrame.setVisible(true);
            horasField.setEditable(false);
            minutosField.setEditable(false);
            segundosField.setEditable(false);
            horasField.setText("0");
            minutosField.setText("0");
            segundosField.setText("0");
        } else {
            horasField.setEditable(true);
            minutosField.setEditable(true);
            segundosField.setEditable(true);
            horasField.setText(Reloj.getHoras());
            minutosField.setText(Reloj.getMinutos());
            segundosField.setText(Reloj.getSegundos());
        }
        nivel = Configuracion.getNivel();
        reloj = Configuracion.getReloj();
        lado = Configuracion.getLado();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivelGroup = new javax.swing.ButtonGroup();
        relojGroup = new javax.swing.ButtonGroup();
        posicionGroup = new javax.swing.ButtonGroup();
        SizeButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        facilButton = new javax.swing.JRadioButton();
        intermedioButton = new javax.swing.JRadioButton();
        dificilButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        siButton = new javax.swing.JRadioButton();
        timerButton = new javax.swing.JRadioButton();
        noButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        izquierdaButton = new javax.swing.JRadioButton();
        derechaButton = new javax.swing.JRadioButton();
        relojFrame = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        horasField = new javax.swing.JTextField();
        minutosField = new javax.swing.JTextField();
        segundosField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        multinivelButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        CincoButton = new javax.swing.JRadioButton();
        SeisButton = new javax.swing.JRadioButton();
        SieteButton = new javax.swing.JRadioButton();
        OchoButton = new javax.swing.JRadioButton();
        NueveButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText("Configuración");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 19, 174, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("1. Nivel:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 73, -1));

        nivelGroup.add(facilButton);
        facilButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        facilButton.setSelected(true);
        facilButton.setText("Fácil");
        facilButton.setToolTipText("");
        facilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 98, -1));

        nivelGroup.add(intermedioButton);
        intermedioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        intermedioButton.setText("Intermedio");
        intermedioButton.setToolTipText("");
        intermedioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intermedioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(intermedioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 116, -1));

        nivelGroup.add(dificilButton);
        dificilButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        dificilButton.setText("Difícil");
        dificilButton.setToolTipText("");
        dificilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dificilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 116, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("3. Posición de la ventana del panel de dígitos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 393, -1));

        relojGroup.add(siButton);
        siButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        siButton.setSelected(true);
        siButton.setText("Sí");
        siButton.setToolTipText("");
        siButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siButtonActionPerformed(evt);
            }
        });
        getContentPane().add(siButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 98, -1));

        relojGroup.add(timerButton);
        timerButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        timerButton.setText("Timer");
        timerButton.setToolTipText("");
        timerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(timerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 116, -1));

        relojGroup.add(noButton);
        noButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        noButton.setText("No");
        noButton.setToolTipText("");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });
        getContentPane().add(noButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 116, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("2. Reloj:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 73, -1));

        posicionGroup.add(izquierdaButton);
        izquierdaButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        izquierdaButton.setText("Izquierda");
        izquierdaButton.setToolTipText("");
        izquierdaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(izquierdaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 382, 98, -1));

        posicionGroup.add(derechaButton);
        derechaButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        derechaButton.setSelected(true);
        derechaButton.setText("Derecha");
        derechaButton.setToolTipText("");
        derechaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(derechaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 382, 116, -1));

        relojFrame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        relojFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Horas");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        relojFrame.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 67, 24));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Segundos");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        relojFrame.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 0, 69, 24));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Minutos");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        relojFrame.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 0, 65, 24));

        horasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasFieldActionPerformed(evt);
            }
        });
        relojFrame.add(horasField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 71, -1));

        minutosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutosFieldActionPerformed(evt);
            }
        });
        relojFrame.add(minutosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 65, 71, -1));
        relojFrame.add(segundosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 65, 71, -1));

        getContentPane().add(relojFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        saveButton.setBackground(new java.awt.Color(204, 255, 204));
        saveButton.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 79, -1, -1));

        cancelButton.setBackground(new java.awt.Color(255, 102, 102));
        cancelButton.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 142, -1, -1));

        nivelGroup.add(multinivelButton);
        multinivelButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        multinivelButton.setText("Multinivel");
        multinivelButton.setToolTipText("");
        multinivelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multinivelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(multinivelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 116, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setText("4. Tamaño de la cuadrícula:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        SizeButton.add(CincoButton);
        CincoButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        CincoButton.setText("5");
        getContentPane().add(CincoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        SizeButton.add(SeisButton);
        SeisButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        SeisButton.setText("6");
        getContentPane().add(SeisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        SizeButton.add(SieteButton);
        SieteButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        SieteButton.setText("7");
        getContentPane().add(SieteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        SizeButton.add(OchoButton);
        OchoButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        OchoButton.setText("8");
        getContentPane().add(OchoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        SizeButton.add(NueveButton);
        NueveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        NueveButton.setText("9");
        getContentPane().add(NueveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilButtonActionPerformed
        // TODO add your handling code here:
        nivel = "Fácil";
    }//GEN-LAST:event_facilButtonActionPerformed

    private void intermedioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intermedioButtonActionPerformed
        // TODO add your handling code here:
        nivel = "Intermedio";
    }//GEN-LAST:event_intermedioButtonActionPerformed

    private void dificilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificilButtonActionPerformed
        // TODO add your handling code here:
        nivel = "Difícil";
    }//GEN-LAST:event_dificilButtonActionPerformed

    private void siButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siButtonActionPerformed
        // TODO add your handling code here:
        reloj = "Sí";
        relojFrame.setVisible(true);
        horasField.setEditable(false);
        minutosField.setEditable(false);
        segundosField.setEditable(false);
        horasField.setText("0");
        minutosField.setText("0");
        segundosField.setText("0");
    }//GEN-LAST:event_siButtonActionPerformed

    private void timerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerButtonActionPerformed
        // TODO add your handling code here:
        reloj = "Timer";
        relojFrame.setVisible(true);
        horasField.setEditable(true);
        minutosField.setEditable(true);
        segundosField.setEditable(true);
    }//GEN-LAST:event_timerButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
        reloj = "No";
        relojFrame.setVisible(false);
    }//GEN-LAST:event_noButtonActionPerformed

    private void izquierdaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaButtonActionPerformed
        // TODO add your handling code here:
        lado = false;
    }//GEN-LAST:event_izquierdaButtonActionPerformed

    private void derechaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaButtonActionPerformed
        // TODO add your handling code here:
        lado = true;
    }//GEN-LAST:event_derechaButtonActionPerformed

    private void horasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasFieldActionPerformed

    private String getSizeButton() {
        for (Enumeration<AbstractButton> buttons = SizeButton.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (!noButton.isSelected()){
            String horas = horasField.getText();
            String minutos = minutosField.getText();
            String segundos = segundosField.getText();
                if (timerButton.isSelected()){
                // validación de las horas, minutos y segundos
                try{
                    Reloj.validarEntrada(horas, 0, 2);
                } catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Las horas deben ser un número.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                } catch (RangeException e){
                    JOptionPane.showMessageDialog(this, "Las horas deben ser del 0 al 2.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                try{
                    Reloj.validarEntrada(minutos, 0, 59);
                } catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Los minutos deben ser un número.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                } catch (RangeException e){
                    JOptionPane.showMessageDialog(this, "Los minutos deben ser del 0 al 59.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                try{
                    Reloj.validarEntrada(segundos, 0, 59);
                } catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Los segundos deben ser un número.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                } catch (RangeException e){
                    JOptionPane.showMessageDialog(this, "Los segundos deben ser del 0 al 59.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // si los tres son 0, enviamos un error
                if (horas.equals("0") && minutos.equals("0") && segundos.equals("0")){
                    JOptionPane.showMessageDialog(this, "Al menos un valor no debe ser 0.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            Reloj.setHoras(horas);
            Reloj.setMinutos(minutos);
            Reloj.setSegundos(segundos);   
        }
        
        Configuracion.setNivel(nivel);
        Configuracion.setReloj(reloj);
        Configuracion.setLado(lado);
        Configuracion.setTamaño(Integer.parseInt(getSizeButton()));
        JOptionPane.showMessageDialog(this, "¡Configuración guardada con éxito!");
        dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void minutosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutosFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

      private void multinivelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multinivelButtonActionPerformed
            // TODO add your handling code here:
            nivel = "Multinivel";
      }//GEN-LAST:event_multinivelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CincoButton;
    private javax.swing.JRadioButton NueveButton;
    private javax.swing.JRadioButton OchoButton;
    private javax.swing.JRadioButton SeisButton;
    private javax.swing.JRadioButton SieteButton;
    private javax.swing.ButtonGroup SizeButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton derechaButton;
    private javax.swing.JRadioButton dificilButton;
    private javax.swing.JRadioButton facilButton;
    private javax.swing.JTextField horasField;
    private javax.swing.JRadioButton intermedioButton;
    private javax.swing.JRadioButton izquierdaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField minutosField;
    private javax.swing.JRadioButton multinivelButton;
    private javax.swing.ButtonGroup nivelGroup;
    private javax.swing.JRadioButton noButton;
    private javax.swing.ButtonGroup posicionGroup;
    private javax.swing.JPanel relojFrame;
    private javax.swing.ButtonGroup relojGroup;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField segundosField;
    private javax.swing.JRadioButton siButton;
    private javax.swing.JRadioButton timerButton;
    // End of variables declaration//GEN-END:variables
}
