/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.programa3.GUI;

import poo.programa3.Marca;
import poo.programa3.Configuracion;
import javax.swing.DefaultListModel;

/**
 * Ventana para el Top 10
 * @author dandi
 */
public class Top10Frame extends javax.swing.JFrame {
      private DefaultListModel FacilListNombreModel;
      private DefaultListModel IntermedioListNombreModel;
      private DefaultListModel DificilListNombreModel;
      private DefaultListModel FacilListTiempoModel;
      private DefaultListModel IntermedioListTiempoModel;
      private DefaultListModel DificilListTiempoModel;
      /**
       * Creates new form Top10Frame
       */
      public Top10Frame() {
            initComponents();
            FacilListNombreModel = new DefaultListModel();
            FacilListNombre.setModel(FacilListNombreModel);
            IntermedioListNombreModel = new DefaultListModel();
            IntermedioListNombre.setModel(IntermedioListNombreModel);
            DificilListNombreModel = new DefaultListModel();
            DificilListNombre.setModel(DificilListNombreModel);
            FacilListTiempoModel = new DefaultListModel();
            FacilListTiempo.setModel(FacilListTiempoModel);
            IntermedioListTiempoModel = new DefaultListModel();
            IntermedioListTiempo.setModel(IntermedioListTiempoModel);
            DificilListTiempoModel = new DefaultListModel();
            DificilListTiempo.setModel(DificilListTiempoModel);
            FillFacilListModel(Configuracion.getTamaño());
            FillIntermedioListModel(Configuracion.getTamaño());
            FillDificilListModel(Configuracion.getTamaño());
            sizeBox.addItem("5");
            sizeBox.addItem("6");
            sizeBox.addItem("7");
            sizeBox.addItem("8");
            sizeBox.addItem("9");
            sizeBox.setSelectedItem(Configuracion.getTamaño() + "");
        }
      
    /**
     * Función que llena la lista del Top 10 del nivel fácil
     * @param size
     */
    public void FillFacilListModel (int size){
        if (FacilListNombreModel != null){
           FacilListNombreModel.removeAllElements();
           FacilListTiempoModel.removeAllElements();
        } else {
            return;
        }
        int i = 0;
        for (Marca marca : Marca.marcasMap.get(size).get("Fácil")){
           FacilListNombreModel.addElement((i+1) + "- " + marca.getNombre());
           FacilListTiempoModel.addElement(Marca.convertToString(marca.getTiempo()));
           i++;
        }
      }
      
    /**
     * Función que llena la lista del Top 10 del nivel Intermedio
     * @param size
     */
    public void FillIntermedioListModel (int size){
            if (IntermedioListNombreModel != null){
               IntermedioListNombreModel.removeAllElements();
               IntermedioListTiempoModel.removeAllElements();
          }
            int i = 0;
          for (Marca marca : Marca.marcasMap.get(size).get("Intermedio")){
               IntermedioListNombreModel.addElement((i+1) + "- " + marca.getNombre());
               IntermedioListTiempoModel.addElement(Marca.convertToString(marca.getTiempo()));
               i++;
          }
      }
      
    /**
     * Función que llena la lista del Top 10 del nivel difícil
     * @param size
     */
    public void FillDificilListModel (int size){
            if (DificilListNombreModel != null){
               DificilListNombreModel.removeAllElements();
               DificilListTiempoModel.removeAllElements();
            }
            int i = 0;
            for (Marca marca : Marca.marcasMap.get(size).get("Difícil")){
               DificilListNombreModel.addElement((i+1) + "- " + marca.getNombre());
               DificilListTiempoModel.addElement(Marca.convertToString(marca.getTiempo()));
               i++;
            }
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FacilListNombre = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        IntermedioListNombre = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        DificilListNombre = new javax.swing.JList<>();
        CerrarButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        FacilListTiempo = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        IntermedioListTiempo = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        DificilListTiempo = new javax.swing.JList<>();
        sizeBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setText("Top 10");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Tamaño de cuadrícula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("NIVEL INTERMEDIO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("NIVEL DIFÍCIL:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        FacilListNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(FacilListNombre);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, 140));

        IntermedioListNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(IntermedioListNombre);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 130, 150));

        DificilListNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(DificilListNombre);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 130, 160));

        CerrarButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CerrarButton.setText("Cerrar");
        CerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 100, 50));

        FacilListTiempo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(FacilListTiempo);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, 140));

        IntermedioListTiempo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(IntermedioListTiempo);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 130, 150));

        DificilListTiempo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(DificilListTiempo);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 130, 160));

        sizeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(sizeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setText("NIVEL FÁCIL:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void CerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarButtonActionPerformed
            // TODO add your handling code here:
            dispose();
      }//GEN-LAST:event_CerrarButtonActionPerformed

    private void sizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeBoxActionPerformed
        // TODO add your handling code here:
            FillFacilListModel(Integer.parseInt((String)sizeBox.getSelectedItem()));
            FillIntermedioListModel(Integer.parseInt((String)sizeBox.getSelectedItem()));
            FillDificilListModel(Integer.parseInt((String)sizeBox.getSelectedItem()));
    }//GEN-LAST:event_sizeBoxActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Top10Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Top10Frame().setVisible(true);
                  }
            });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarButton;
    private javax.swing.JList<String> DificilListNombre;
    private javax.swing.JList<String> DificilListTiempo;
    private javax.swing.JList<String> FacilListNombre;
    private javax.swing.JList<String> FacilListTiempo;
    private javax.swing.JList<String> IntermedioListNombre;
    private javax.swing.JList<String> IntermedioListTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> sizeBox;
    // End of variables declaration//GEN-END:variables
}
