package poo.programa3.vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dandi
 */
import poo.programa3.modelo.Juego;
import poo.programa3.modelo.Configuracion;
import javax.swing.JOptionPane;
import java.util.ArrayList;

public class Posibles extends javax.swing.JFrame {

      /**
       * Creates new form Posibles
       */
      public Posibles() {
            initComponents();
            this.setLocationRelativeTo(null);
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            FindButton = new javax.swing.JButton();
            FilaTXT = new javax.swing.JTextField();
            ColumnaTXT = new javax.swing.JTextField();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
            jLabel1.setText("Posibles jugadas");

            jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
            jLabel2.setText("Fila");

            jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
            jLabel3.setText("Columna");

            FindButton.setText("Buscar");
            FindButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        FindButtonActionPerformed(evt);
                  }
            });

            FilaTXT.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

            ColumnaTXT.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(64, 64, 64)
                                    .addComponent(FilaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(FindButton)
                                                .addGap(75, 75, 75))
                                          .addComponent(ColumnaTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(FilaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(ColumnaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(FindButton)
                        .addContainerGap(22, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void FindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonActionPerformed
            // TODO add your handling code here:
            int fila = 0;
            int columna = 0;
            try {
                  fila = Integer.valueOf(FilaTXT.getText());
                  columna = Integer.valueOf(ColumnaTXT.getText());
                  if (fila > Configuracion.getTamaño() || fila < 1 || columna > Configuracion.getTamaño() || columna < 1) {
                        throw new ArithmeticException("message");
                  }
            }
            catch (Exception e){
                  JOptionPane.showMessageDialog(this, "ESOS NÚMEROS NO SON VÁLIDOS.", 
                "Error", JOptionPane.ERROR_MESSAGE);
                  return;
            }
            fila -= 1;
            columna -= 1;
            
            // Check columna
            Juego juego = JugarFrame.getJuego();
            javax.swing.JButton [][] casillas = juego.getCasillas();
            ArrayList<Integer> posibles = new ArrayList<>();
            for (int i = 0; i < Configuracion.getTamaño(); i++){
                  if (!casillas[fila][i].getText().equals("")){
                        posibles.add(Integer.valueOf(casillas[fila][i].getText()));
                  }
                  if (!casillas[i][columna].getText().equals("")){
                        posibles.add(Integer.valueOf(casillas[i][columna].getText()));
                  }
            }
            String texto = "Las jugadas posibles son: ";
            OUTER:
            for (int i = 1; i <= Configuracion.getTamaño(); i++){
                  for (Integer num : posibles){
                        if (i == num){
                              continue OUTER; 
                        }
                  }
                  texto += " " + i;
            }
            
            JOptionPane.showMessageDialog(this, texto); 
            dispose();
      }//GEN-LAST:event_FindButtonActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Posibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Posibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Posibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Posibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Posibles().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JTextField ColumnaTXT;
      private javax.swing.JTextField FilaTXT;
      private javax.swing.JButton FindButton;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      // End of variables declaration//GEN-END:variables
}
